### ISSUE TITLE
Add information about how complete the exported data is

### ISSUE THREAD

**Issue by allo-** [daviddavo/jgmd#41]
# Backstory

Some services provide more data (using the methods listed on the site) than others, and some may provide little data using the easy way and more data when using a more complicated way.

### Example: Twitter
The Twitter data export contains much more data since some time, including information on advertisers, login IPs, and other technical data.

### Example: Spotify
Using the method on your website, you get some information about your bookmarks and playback history, but most GDPR relevant data is not contained in the archive.

People who requested their data using GDRP (I am not sure if by e-mail or even by sending a letter) got archives that contain much more personal and technical data, like the brand name of their Bluetooth headphones.

# Improvement suggestion:

- List what data is contained in the export
- List what data is missing (if known)
- List what other ways may be available to get more data

**Comment by daviddavo** [comment]
This is now available on the fork [justwhatsthedata.github.io](https://justwhatsthedata.github.io/)
